import Head from "next/head";
import Image from "next/image";
import { DiHtml5, DiJavascript1, DiReact } from "react-icons/di";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { SiTailwindcss, SiBootstrap, SiNodedotjs, SiPostgresql, SiFigma } from "react-icons/si";

import deved from "../public/dev-ed-wave.png";
import { useState } from "react";
import Footer from "./components/Footer";

import { motion } from "framer-motion";

import portfolioCardData from "../data/portfolioCardData";
import PortfolioSection from "./components/PortfolioSection";


export default function Home (props) {
  const [darkMode, setDarkMode] = useState(false);
  const {projects}=props


  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Li Wang Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">

          {/* ============Nav ===========*/}

          <nav className="py-10 mb-12 flex justify-between">
            <motion.div
              initial={{ rotate: 0 }}
              animate={{ rotate: 360 }}
              transition={{ duration: 10, repeat: Infinity }}
            >
              <Image src="/logo3.png" alt="logo" width={100} height={100} objectFit="cover" />
            </motion.div>

            {/* <Image src="/logo.png" alt="logo" width={100} height={100} /> */}
            {/* <h1 className="font-burtons">Li"s Portfolio</h1> */}
            <ul className="flex items-center gap-3">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer dark:text-gray-200" />
              </li>
              <li>
                {/* <a className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-3 py-2 rounded-md" href="#">Resume</a> */}
                <a className=" bg-gradient-to-r from-orange-600 to-purple-800  text-white px-3 py-2 rounded-md" href="#">Resume</a>
              </li>
            </ul>
          </nav>


          {/* ============Hero ===========*/}


          <div className="text-center p-10">
            <h2 className="text-4xl py-2 text-purple-800 font-medium md:text-6xl">Hi there...</h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">Frontend Development Student in Hyperisland</h3>
            <p className="text-medium py-5 leading-8   text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-200">
              I am Li Wang. I have been worked in the field of environmental assessment for many years. But now I am passionate about building beautiful and functional web applications. I am looking for a internships in the <span className="text-purple-800">Frontend Development</span> / <span className="text-purple-800">Fullstack Development</span> areas to help me improve my skills in the real world.
            </p>
        
          </div>
          


          {/* ============Avatar ===========*/}

          <div className="relative mx-auto bg-gradient-to-b from-purple-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover" alt="avatar"/>
          </div>
        </section>


        {/* =============Portfolio Section ===========*/}


        <section>
          <div className="text-center p-10">
            <h3 className="text-3xl py-1  dark:text-white">Tech</h3>
            <p className="text-md py-2 leading-8 text-gray-800 md:text-lg dark:text-gray-200">
              Since the beginning of my journey as a frontend student in Hyperisland, I have been working with different technologies and frameworks.
              I have been working with <span className="text-purple-800">Html, Css, Javascript, React, Next.js, TailwindCSS, Bootstrap </span>and more.I have also been working with <span className="text-purple-800">Node.js, Express, Postgres SQL</span> and <span className="text-purple-800">Figma</span>.
            </p>

            <p className="text-md py-2 leading-8 text-gray-800 md:text-lg dark:text-gray-200">
              I am looking for internships in the <span className="text-purple-800">Frontend Development</span> & <span className="text-purple-800">Fullstack Development</span> areas.
            </p>
          </div>

          <div className="text-4xl flex justify-center gap-10 pb-10 text-purple-700 md:text-5xl dark:text-gray-200">
            <DiHtml5 />
            <DiJavascript1/>
            <DiReact />
            <SiTailwindcss />
            <SiBootstrap />
            <SiNodedotjs />
            <SiPostgresql />
            <SiFigma/>
          </div>

          <h3 className=" text-center text-3xl py-3  dark:text-white">Portfolio</h3>

          <div className="lg:flex gap-10 ">
            <PortfolioSection projects={portfolioCardData} />
          </div>

        </section>
      </main>
      <Footer />
    </div>
  );
}
